### PR TITLE
Rename "payments" table to "payment"

### PR DESCRIPTION
**Pull request by moiikana**
- database tables should be in singular
- also rename payment_id table to last_generated_payment_id to make clear this is primarily a store for IDs that have been generated before

### CODE REVIEW

**Review by gbirke — APPROVED** [review]

**Comment by Abban** [comment]
IMO tables are plural and entities are singular?

**Comment by moiikana** [comment]
>IMO tables are plural and entities are singular?
Gabriel and I had a chat about that, we decided to at least keep it consistent for everything.
in German schools you keep the database tables singular too because "they contain 1 entity" of an object that connects to other things. Just like with the entity classes in the code. That was the philosophy I was taught. 
For consistency reasons I would prefer to stick to singular in table names AND in the code.
If you have strong feelings against this we can of course have another team chat about it to discuss!

The reason for the renaming was that I already noticed an error happening related to that in some config.

**Comment by Abban** [comment]
A table holds a collection of entities though. Naming them singular makes it seem like it contains only a single row.

**Comment by Abban** [comment]
Thinking about it further SQL currently looks something like this:

`SELECT * FROM payment`

Which doesn't read well as the query returns multiple entities

**Comment by moiikana** [comment]
I see it in a way of "Entity Relationship modelling / structuring" of the data. Same as with objects/classes in the code.

>SELECT * FROM payment
I'm personally very used to this abstraction :D so I'm not feeling the problem there. Not more than it would also mean for the code

**Comment by Abban** [comment]
Doctrine's examples also have plural table names https://www.doctrine-project.org/projects/doctrine-orm/en/current/tutorials/getting-started.html

**Comment by moiikana** [comment]
there are some more points, circuling around prefering "uninflected nouns" which I also think is actually a thing because typos will happen.
https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names

>Customers.Address

that would be a readability example against plural. when accessing a property of an entity you want to express that it's from 1 entity

**Pull request merged**
